import React from 'react'

const Instamart = () => {
  return (
    <div>
        <h1>Welcome to Instamart </h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur reprehenderit dolorem optio excepturi, vel tenetur odio ad quaerat neque deserunt exercitationem distinctio quasi accusamus placeat unde pariatur, provident quas eligendi temporibus assumenda a facilis minima veritatis. Unde ipsum quibusdam quo, rerum explicabo officiis ex eaque corporis accusantium est molestias praesentium laudantium architecto delectus ratione laborum maxime! Quasi architecto ducimus aspernatur atque quia ipsa, accusantium consequatur pariatur animi sequi ex ipsam eum, ea quaerat quisquam incidunt consequuntur veniam commodi excepturi fugiat. Tempora quos quae magni corporis itaque maxime voluptate incidunt nesciunt, porro maiores quisquam reiciendis quia harum voluptates assumenda hic mollitia vero obcaecati aliquid, autem numquam velit praesentium? Aliquid, odio magnam. In culpa dolor possimus aliquam porro, et temporibus itaque, maiores, asperiores alias neque repudiandae modi sit error. Ipsum, modi nulla repellendus, odio vero eius libero beatae quas debitis neque explicabo pariatur quae quis error facere. Odit quasi sequi cumque inventore aliquid, eius laudantium. Ut voluptatibus sunt beatae dolores nobis vitae omnis commodi, culpa numquam voluptates cupiditate harum, esse hic eligendi suscipit consequatur quo. Provident expedita a doloribus maiores autem adipisci, optio odio atque saepe, in exercitationem perferendis numquam placeat corporis! Unde quod earum maiores explicabo voluptatibus vel praesentium voluptas eum, ad architecto natus repellat eos placeat provident, iure laboriosam exercitationem incidunt. Numquam quibusdam quaerat voluptas unde, deleniti perspiciatis consequatur minima necessitatibus fuga expedita, molestiae repudiandae itaque quo? Voluptate iste dicta eius dolorum dolor blanditiis alias unde, temporibus beatae cum ullam quibusdam reprehenderit provident doloribus deserunt exercitationem quisquam quam veniam nihil voluptatum officia! Libero quia eveniet sint error alias optio, dolores modi at praesentium ex reprehenderit repellat similique animi? Consequatur, mollitia consectetur nam libero eius molestias repudiandae inventore sequi dolores voluptatem quasi provident accusantium eligendi iusto voluptates facilis numquam assumenda veritatis esse aut voluptate explicabo incidunt. Aperiam velit dolorem aspernatur nobis non, minus, saepe fugit libero inventore dignissimos voluptate ducimus pariatur illo voluptatum recusandae accusamus earum qui quasi nesciunt laudantium deleniti magnam eveniet. Dolorum sequi sint odio, alias saepe assumenda temporibus enim excepturi facilis, ducimus ipsa repellat minus ut non repudiandae laborum aut quaerat accusantium aliquam perferendis quibusdam labore! Laboriosam, accusamus?</p>
    </div>
  )
}

export default Instamart